#https://stackoverflow.com/questions/28097064/dockerignore-ignore-everything-except-a-file-and-the-dockerfile

# Ignore Everything
**

# do not ignore
!funnel
!README.md
!uv.lock
!pyproject.toml

# remove all pyc files and __pycache__ folders
**/__pycache__
**/*.pyc
